# Generated by Django 6.0.7 on 2026-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
    ]
