# Generated by Django 6.0.7 on 2026-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_alter_otp_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
