# Generated by Django 6.0.7 on 2026-08-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp_bio_otp_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
